---
#first time ./ansible-playbook_wrapper configure_host.yml -u yourgenericaccount -Kk
#second time ./ansible-playbook_wrapper configure_host.yml -K

- hosts: rancher-masters
  gather_facts: no
  pre_tasks:
  - name: Install epel
    yum:
      name: epel-release
      state: latest
    become: yes
#  roles:
#  - configure-ops-accounts

- hosts: rancher-masters
  gather_facts: no
  roles:
  - configure-hostname
  - configure-ssh
  - docker
#  post_tasks:
#  - name: Remove former ops users
#    user: name="{{ item.name}}" groups="adm,sudo" shell="/bin/bash" home="/home/{{item.name}}" password="{{ item.password }}" state=absent
#    with_items: '{{former_ops_users}}'
#    become: yes
