---
- name: install pip
  yum:
    name: python-pip
    state: latest

- name: Install docker-py
  pip: name=docker-py version="{{dockerpy_version}}"
  become: yes

- name: Add yum repo
  yum_repository:
    name: docker
    description: docker repo
    baseurl: https://yum.dockerproject.org/repo/main/centos/7/
    gpgkey: https://yum.dockerproject.org/gpg
    gpgcheck: yes
    enabled: yes

- name: Install Docker package
  yum:
    name: docker-engine
    update_cache: yes
  become: yes
  notify: Restart docker

- name: Create a docker group
  group:
    name: docker
    state: present
  become: yes

- name: Start docker
  service: name=docker state=started
  become: yes