---
- name: Ensure lvm required packages are installed
  yum: pkg={{ item }} state=latest
  with_items:
    - lvm2
    - parted
  become: yes

- name: Create LVM volume group
  lvg:
    pvs: "{{diskname}}"
    state: present
    vg: "{{vg_name}}"
  become: yes

- name: Create LVM logical volume
  lvol:
    vg: "{{vg_name}}"
    lv: "{{lv_name}}"
    size: 100%VG
    force: yes
  become: yes

- name: Format partition
  filesystem: fstype=ext4 dev=/dev/{{vg_name}}/{{lv_name}} resizefs=yes
  become: yes

- name: Mount partition
  mount: name={{mount_point}} src="/dev/{{vg_name}}/{{lv_name}}" fstype=ext4 state=mounted
  become: yes

